pipeline {
     agent any
     tools{
          maven 'MAVEN'
          }
        environment {
        //once you create ACR in Azure cloud, use that here
        registryName = "claimsservice"
        //- update your credentials ID after creating credentials for connecting to ACR
        registryCredential = '6406f9c7-9ae3-42ba-9a55-38efba7f51cf'
        dockerImage = ''
        registryUrl = 'claimsservice.azurecr.io'
    }

    stages {

        stage ('checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/Praneetha_changes']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Development456/ClaimsApp.git']]])
            }
        }

        stage ('Build Docker image') {
            steps {

                script {
                sh 'docker build -t claims-0.0.1-SNAPSHOT.jar'
//                     sh 'sudo usermod -a -G docker jenkins'
//                     dockerImage = docker.build registryName
                }
            }
        }
    }
