pipeline {
	agent none
  stages {
  	stage('Maven Install') {
    	agent {
      	docker {
        	image 'maven:3.5.0'
        }
      }
      steps {
      	sh 'mvn clean install'
      }
    }
    stage('Docker Build') {
    	agent any
      steps {
	      dir('Claims API/claims'){     
      	sh 'docker build -t apurva09/claims-docker.jar .'
        }
      }      
    }
  }
}
